/**
 * Join-token auth for Members.
 *
 * MVP: tokens defined in /config/tokens.yaml, hashed with SHA-256.
 * (Full management UI lands in M7; for now the file is hand-edited or
 * generated by future API endpoints.)
 *
 * tokens.yaml format:
 *   tokens:
 *     - id: short-id
 *       name: laptop-fleet
 *       hash: sha256:<hex>
 *       created_at: 2026-04-26T10:00:00Z
 *       created_by: filiph
 *       revoked_at: null
 *       usage:
 *         - member_id: <uuid>
 *           member_name: alice
 *           connected_at: 2026-04-26T10:01:00Z
 */

import { createHash, randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'
import { parse, stringify } from 'yaml'

export interface TokenRecord {
	id: string
	name: string
	hash: string
	created_at: string
	created_by: string
	revoked_at: string | null
	revoked_by?: string
	usage?: TokenUsage[]
}

export interface TokenUsage {
	member_id: string
	member_name: string
	connected_at: string
}

interface TokensFile {
	tokens: TokenRecord[]
}

function hashToken(raw: string): string {
	return 'sha256:' + createHash('sha256').update(raw).digest('hex')
}

export class TokenStore {
	constructor(private readonly path: string) {}

	private load(): TokensFile {
		if (!existsSync(this.path)) {
			return { tokens: [] }
		}
		const raw = readFileSync(this.path, 'utf8')
		const parsed = parse(raw) as TokensFile | null
		return parsed ?? { tokens: [] }
	}

	private save(data: TokensFile): void {
		mkdirSync(dirname(this.path), { recursive: true })
		writeFileSync(this.path, stringify(data), 'utf8')
	}

	list(): TokenRecord[] {
		return this.load().tokens
	}

	/**
	 * Validate a presented token. Returns the matching record (and updates
	 * usage audit) or null if no match / revoked.
	 */
	validate(rawToken: string): TokenRecord | null {
		const data = this.load()
		const hash = hashToken(rawToken)
		const match = data.tokens.find((t) => t.hash === hash && t.revoked_at === null)
		return match ?? null
	}

	recordUsage(tokenId: string, usage: TokenUsage): void {
		const data = this.load()
		const t = data.tokens.find((x) => x.id === tokenId)
		if (!t) return
		t.usage = t.usage ?? []
		t.usage.push(usage)
		this.save(data)
	}

	/**
	 * Earliest known connection timestamp for a given member_id, scanned across
	 * all token usage logs. Used to surface "first seen" in the dashboard so
	 * stale stored state from an earlier life of the same member_id is visible.
	 */
	findFirstConnectionForMember(memberId: string): Date | null {
		let earliest: Date | null = null
		for (const t of this.load().tokens) {
			for (const u of t.usage ?? []) {
				if (u.member_id !== memberId) continue
				const d = new Date(u.connected_at)
				if (Number.isNaN(d.getTime())) continue
				if (!earliest || d < earliest) earliest = d
			}
		}
		return earliest
	}

	/**
	 * Create a new token. Returns the raw token (only chance to see it) and
	 * the stored record.
	 */
	create(name: string, createdBy: string): { raw: string; record: TokenRecord } {
		const raw = randomBytes(32).toString('base64url')
		const id = randomBytes(6).toString('base64url')
		const record: TokenRecord = {
			id,
			name,
			hash: hashToken(raw),
			created_at: new Date().toISOString(),
			created_by: createdBy,
			revoked_at: null,
			usage: [],
		}
		const data = this.load()
		data.tokens.push(record)
		this.save(data)
		return { raw, record }
	}

	revoke(id: string, revokedBy: string): boolean {
		const data = this.load()
		const t = data.tokens.find((x) => x.id === id)
		if (!t || t.revoked_at !== null) return false
		t.revoked_at = new Date().toISOString()
		t.revoked_by = revokedBy
		this.save(data)
		return true
	}
}
