/**
 * Interactive helper that assembles an `mcp.yaml` for a Member.
 *
 *   npm run member:generate-mcp-config              # interactive → <repo-root>/mcp.yaml
 *   npm run member:generate-mcp-config -- ./x.yaml  # custom path
 *   npm run member:generate-mcp-config -- --template # write the full commented catalog
 *
 * Interactive mode walks the {@link KNOWN_SERVERS} catalog: pick the services
 * you want, choose read-only (default) vs full tool access, and the script
 * writes a `mcp.yaml` plus prints the `.env.member` lines you still need to
 * fill in. Secrets are referenced as `${VAR}` so the YAML stays commit-safe.
 *
 * Writing directly (not a `>` redirect) keeps npm's `> @night/member …` script
 * header out of the file. Refuses to overwrite without `--force`. Falls back to
 * the static template when stdin isn't a TTY (CI / piped).
 */

import { existsSync, writeFileSync } from 'node:fs'
import { isAbsolute, resolve } from 'node:path'
import { createInterface } from 'node:readline/promises'
import { stringify as stringifyYaml } from 'yaml'
import { findRepoRoot } from './schedule.ts'
import { catalogServerEntry, defaultMcpConfigYaml, KNOWN_SERVERS } from './agent/mcp-config.ts'

const args = process.argv.slice(2)
const force = args.includes('--force')
const wantTemplate = args.includes('--template')
const positional = args.filter((a) => !a.startsWith('--'))
const target = resolveTarget(positional[0])

if (!force && existsSync(target)) {
	fail(`${target} already exists.\n` + `Pass --force to overwrite, or edit the file by hand.\n`)
}

if (wantTemplate || !process.stdin.isTTY) {
	if (!wantTemplate) {
		process.stderr.write('stdin is not a TTY — writing the full commented template.\n')
	}
	writeFileSync(target, defaultMcpConfigYaml())
	process.stderr.write(`Wrote ${target} (catalog template; uncomment what you want).\n`)
	process.exit(0)
}

await interactive()

async function interactive(): Promise<void> {
	const rl = createInterface({ input: process.stdin, output: process.stdout })
	const out = (s = '') => process.stdout.write(s + '\n')

	out('\nNight Family — MCP config generator')
	out('Pick the services this member should reach. Secrets stay in .env.member.\n')
	KNOWN_SERVERS.forEach((s, i) => {
		out(`  ${String(i + 1).padStart(2)}. ${s.title}  [${s.authBucket}]`)
		out(`      ${s.notes}`)
	})
	out('')

	const pick = await rl.question('Servers to enable (e.g. 1,3,4 — blank to cancel): ')
	const chosen = parsePicks(pick, KNOWN_SERVERS.length)
	if (chosen.length === 0) {
		out('Nothing selected — aborting.')
		rl.close()
		return
	}

	const servers: Record<string, unknown> = {}
	const envVars = new Set<string>()
	for (const idx of chosen) {
		const server = KNOWN_SERVERS[idx]!
		out(`\n• ${server.title}`)
		const readOnly = await yesNo(rl, '  Read-only tools only (recommended)?', true)
		servers[server.key] = catalogServerEntry(server, readOnly)
		for (const sec of server.secrets) envVars.add(sec.env)
		if (!readOnly) {
			out('  ⚠ full tool access — this server can take write actions on your behalf.')
		}
	}
	rl.close()

	const yaml = renderConfig(servers)
	writeFileSync(target, yaml)
	out(`\nWrote ${target}`)

	if (envVars.size > 0) {
		out('\nAdd these to .env.member (the YAML references them as ${VAR}):')
		for (const v of [...envVars].sort()) out(`  ${v}=`)
	}
	out(
		'\nHeads-up: package & tool names come from a catalog and drift over time —' +
			'\nverify them against each server’s docs, then restart the member.\n',
	)
}

function renderConfig(servers: Record<string, unknown>): string {
	const header =
		'# Night Family member — MCP servers. Generated by generate-mcp-config.\n' +
		'# Secrets are referenced as ${VAR}; set them in .env.member.\n' +
		'# `allow` is a read-only allowlist; widen it deliberately. A server that\n' +
		'# fails to connect is skipped, never blocking task execution.\n\n'
	return header + stringifyYaml({ mcpServers: servers })
}

async function yesNo(
	rl: ReturnType<typeof createInterface>,
	prompt: string,
	def: boolean,
): Promise<boolean> {
	const ans = (await rl.question(`${prompt} ${def ? '[Y/n]' : '[y/N]'} `)).trim().toLowerCase()
	if (ans === '') return def
	return ans === 'y' || ans === 'yes'
}

function parsePicks(raw: string, max: number): number[] {
	const picks = new Set<number>()
	for (const part of raw.split(',')) {
		const n = Number.parseInt(part.trim(), 10)
		if (Number.isInteger(n) && n >= 1 && n <= max) picks.add(n - 1)
	}
	return [...picks].sort((a, b) => a - b)
}

function resolveTarget(arg: string | undefined): string {
	if (arg) return isAbsolute(arg) ? arg : resolve(process.cwd(), arg)
	const root = findRepoRoot()
	if (!root) {
		fail(
			`Could not locate the night-family repo root from ${process.cwd()}.\n` +
				`Pass an explicit path: ... generate-mcp-config -- /path/to/mcp.yaml\n`,
		)
	}
	return resolve(root!, 'mcp.yaml')
}

function fail(msg: string): never {
	process.stderr.write(msg)
	process.exit(2)
}
